"""Increase password column length

Revision ID: 694482ca3e89
Revises: 0607688fbd4e
Create Date: 2025-04-27 21:36:50.513630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694482ca3e89'
down_revision = '0607688fbd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
